require("konze.plugins-setup")
require("konze.core.options")
require("konze.core.keymaps")
require("konze.core.colorscheme")
require("konze.plugins.comment")
require("konze.plugins.nvim-tree")
require("konze.plugins.lualine")
require("konze.plugins.telescope")
require("konze.plugins.nvim-cmp")

