require("konze.plugins-setup")
require("konze.core.options")
require("konze.core.keymaps")
require("konze.core.colorscheme")
require("konze.plugins.comment")
require("konze.plugins.nvim-tree")
require("konze.plugins.lualine")
require("konze.plugins.telescope")
require("konze.plugins.nvim-cmp")
require("konze.plugins.lsp.mason")
require("konze.plugins.lsp.lspconfig")
require("konze.plugins.lsp.lspsaga")
require("konze.plugins.lsp.rust-tools")
require("konze.plugins.treesitter")
require("konze.plugins.codewindow")
require("konze.plugins.nvim-lastplace")
require("konze.plugins.nvim-autopairs")
require("konze.plugins.bufferline")
require("konze.plugins.persisted")
require("konze.plugins.trouble")
require("konze.plugins.gitsigns")
require("konze.plugins.toggleterm")
require("konze.plugins.nvim-dap")
require("konze.plugins.nvim-dap-virtual-text")
require("konze.plugins.nvim-dap-ui")
require("konze.plugins.nvim-dap-python")
--require("konze.plugins.copilot")
--require("konze.plugins.copilot-cmp")
require("konze.plugins.markdown_config")

require("konze.core.autocommands")

vim.api.nvim_command('colorscheme neosolarized')

print("nvim ready!")
